### ISSUE TITLE
Do not require dataclasses on python 3.7+

### ISSUE THREAD

**Issue by yourfate** [python-desert/desert#102]
Python3.7+ comes with the package `dataclasses` built in. Desert fails to install from our internal pypi mirror, as that does not mirror the `dataclasses` packet anymore.

It seems the entry in this file should be made conditional somehow:
https://github.com/python-desert/desert/blob/631de5f98d0f3edd3ecbab57100c5664a43bf3d5/requirements.in#L1-L4

**Comment by altendky** [comment]
So two issues here I think.  First is that `dataclasses` should be conditional on `; python_version < "3.7"`.  Second is that maybe both `dataclasses` and `attrs` should be written as extras instead?  Over in https://github.com/altendky/qtrio I did that for the similar situation of supporting both PyQt5 and PySide2.  Not exactly the same as those are at least somewhat exclusive and desert could certainly work with both `dataclasses` and `attrs` within a single process, but still.

https://github.com/altendky/qtrio/blob/03742c3599b27645b81ce51f3f4776888400a259/setup.py#L52-L53
```
        "pyqt5": ["pyqt5", "pyqt5-stubs"],
        "pyside2": ["pyside2"],
```

I'll go ahead and add the Python version check.  The extras piece can be considered separately.
