### ISSUE TITLE
Optional fields with value None raises exception on load

### ISSUE THREAD

**Issue by sveinse** [python-desert/desert#11]
Running on python 3.8.0 on Windows 10, 32-bit version in a venv. `desert` retrieved from master commit a9b41e1ed3630.

`desert` does not support reading input data containing None from a schema with Optional type. The following test shows the issue:

```
def test_optional_present(module):
    """Including optional with None set the field."""

    @module.dataclass
    class A:
        x: t.Optional[int]

    data = desert.schema_class(A)().load({"x": None})
    assert data == A(None)
````

This will fail with the error: marshmallow.exceptions.ValidationError: {'x': ['Field may not be null.']}. The documentation for `typing.Optional` states that it is equivalent of `Union[X, None]` indicates that `None` is valid input to a `Optional` field.

**Comment by python-desert** [comment]
Thanks for reporting. I can reproduce the issue. I'll try to get it fixed over the weekend.
