### ISSUE TITLE
Disable either travis-ci.org or .com

### ISSUE THREAD

**Issue by altendky** [python-desert/desert#50]
I don't think both are needed?

**Comment by python-desert** [comment]
Travis's .org domain is legacy. .com should be used. https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/

**Comment by altendky** [comment]
Sure.  To be clear, as far as I can tell I can't do anything about this.

**Comment by python-desert** [comment]
Ok. I think I've flipped the setting to disable .org.

**Comment by altendky** [comment]
Looks good over in #49.
