### ISSUE TITLE
Unions and recursive type hints

### ISSUE THREAD

**Issue by python-desert** [python-desert/desert#89]
There are at least two issues going on with our handling of recursive types. 

One is handling of forward references in type hints. Python's representation inside the `typing` module seems to be evolving, and the tools for dealing with them (typing_inspect and pytypes) may be still catching up. I think that's what's catching us in #88.

There is also a general issue about the robustness of our union fields. 

- Theoretically, a greedy recursive descent should serialize fine in simple cases like the one, but the implementation we're using seems to be having problems. There may be some fixes for marshmallow-union that could address this. 
- There are also more complicated situations where greedy strategies will necessarily yield ambiguous parses. We could look into fancier parser generators that could detect and report ambiguities.
- A [more explicit union representation](https://github.com/python-desert/desert/issues/36) would eliminate the issue of ambiguity by simply declaring  what types are being represented.

**Comment by sveinse** [comment]
In the context of serialization, unions must carry additional information to be able to differentiate between the union variant being used, either implicitly via type `Union[str, int]`, or explicitly using a selector field. For this https://github.com/adamboche/python-marshmallow-union or https://github.com/Bachmann1234/marshmallow-polyfield/ exists.

I think it is error prone to rely on implicit type checks, so I think the first design decision would be if desert should extend into explicit union selectors. The downside of adding union selector fields is that the serialized stream adds information; There will be more fields than what the data class or schema suggests.

**Comment by altendky** [comment]
I think that's #36?  It kind of got put on hold while I did some CI stuff for desert and now I'm trying to catchup pyqt5-tools...  I did get a wrapper approach implemented as `ExplicitPolyField` over in https://github.com/Bachmann1234/marshmallow-polyfield/pull/34.

**Comment by python-desert** [comment]
Yeah let's call this a duplicate of https://github.com/python-desert/desert/issues/36.

**Comment by altendky** [comment]
And #88 for the recursion piece mentioned here, I think.
